name: Kontrol
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  
jobs:
  BirlesikGuncelleme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2
        
      - name: Python 3.11.8 YÃ¼kle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.8
          
      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel requests cloudscraper beautifulsoup4
          
      - name: inattv.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python inattv.py
      - name: vav.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python vav.py
      - name: androtv.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python androtv.py
      - name: selcuk.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python selcuk.py
      - name: rec.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python rec.py
      - name: rec2.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python rec2.py
      - name: karsilasmalar.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python karsilasmalar.py
      - name: gbl.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python gbl.py        
      - name: birlestir.py Ã‡alÄ±ÅŸtÄ±r
        continue-on-error: true
        run: python birlestir.py        
      
      - name: DeÄŸiÅŸiklik KontrolÃ¼
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT
          
      - name: DeÄŸiÅŸiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ğŸ”„ Kanallar gÃ¼ncellendi" -m "ğŸ“º Domain kontrolÃ¼ ve M3U gÃ¼ncellemeleri tamamlandÄ±" -m "ğŸ•’ Otomatik iÅŸlem - $GITHUB_SHA"
          git push
